name: Build

permissions:
  contents: read
  security-events: write
  pull-requests: write

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0 # relevant for sonar analysis

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # v6

      - name: Set up JDK 21
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Cache SonarCloud packages
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Gradle cache
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties', '**/*.gradle*', '**/*.versions.toml') }}-${{ hashFiles('**/*.kts') }}
          restore-keys: |
            gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties', '**/*.gradle*', '**/*.versions.toml') }}-
            gradle-${{ runner.os }}-

      - name: Run build
        run: ./gradlew check detekt mergeDetektSarif :gradle-plugins:buildPlugins --no-daemon --warning-mode=all --continue

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: reports
          path: '**/build/reports'

      - uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4
        if: success() || failure()
        with:
          sarif_file: build/detekt-merged.sarif
          category: detekt

      - name: Re-run all tests with Gradle
        run: |
          ./gradlew -p gradle-plugins check
          ./gradlew check

      - name: Report analysis to sonar
        run: ./gradlew sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

