name: Publish


permissions:
  contents: write

concurrency:
  group: publish
  cancel-in-progress: false

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6

      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Gradle cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties', '**/*.gradle*', '**/*.versions.toml') }}-${{ hashFiles('**/*.kts') }}
          restore-keys: |
            gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties', '**/*.gradle*', '**/*.versions.toml') }}-
            gradle-${{ runner.os }}-

      - name: Configure Git
        shell: bash
        run: |
          git config --global user.name "Urs Joss"
          git config --global user.email "urs.joss@gmx.ch"

      - name: Run build
        run: ./gradlew build --no-daemon --warning-mode=all

      - name: Publish github pages
        run: ./gradlew :guide:gitPublishPush --no-daemon --warning-mode=all
        env:
          GRGIT_USER: ${{ secrets.GRGIT_USER }}

      - name: Publish to maven central
        run: ./gradlew :kris-core:publishToMavenCentral :kris-io:publishToMavenCentral -x apiCheck --no-daemon --warning-mode=all
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MC_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MC_PASSWORD }}
